"""create tables locations and stocks

Revision ID: 5dfda7bce45e
Revises: 6c4d6cb3d49e
Create Date: 2026-09-18 11:55:01.740696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfda7bce45e'
down_revision: Union[str, Sequence[str], None] = '6c4d6cb3d49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stocks_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('product_id', 'location_id', name=op.f('uq_stocks_product_id'))
    )
    op.create_index(op.f('ix_stocks_location_id'), 'stocks', ['location_id'], unique=False)
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_location_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
